name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ci-${{ (github.ref == 'refs/heads/master' && github.sha) || (github.event_name == 'pull_request' && github.head_ref) || github.ref }}
  cancel-in-progress: false

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        feature-flag: [ "--no-default-features", "--all-features" ]
        os: [ ubuntu-latest, ubuntu-24.04-arm, macos-26-intel, macos-latest, windows-latest, windows-11-arm ]
      fail-fast: false
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Run tests
      run: cargo +nightly test --verbose ${{ matrix.feature-flag }} -- --nocapture
      timeout-minutes: 20
  benchmarks:
    needs: unit-tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, macos-26-intel, macos-latest, windows-latest, windows-11-arm ]
      fail-fast: false
    permissions:
      contents: write
      deployments: write
      pull-requests: write
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Run benchmarks
      run: cargo +nightly bench --features reproducibility_cross_platform -- --output-format bencher | tee bench-output.txt
      timeout-minutes: 20
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@a7bc2366eda11037936ea57d811a43b3418d3073 # v1.21.0
      with:
        name: Rust Benchmark
        tool: 'cargo'
        output-file-path: bench-output.txt
        github-token: ${{ secrets.GITHUB_TOKEN }}
        summary-always: true
        auto-push: ${{ github.event_name != 'pull_request' }}
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '125%'
        comment-on-alert: true
        fail-on-alert: true